package net.chaosserver.weathernext.weather.scheduler;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.TimeZone;

/**
 * POJO to describe a schedule of emails to send.
 * 
 * @author jreed
 * 
 */
public class WeatherEmailSchedule implements Serializable {
    /** Autogenerated. */
    private static final long serialVersionUID = -5592258067467204179L;

    protected SimpleDateFormat sdf = new SimpleDateFormat(
            "yyyy-MM-dd'T'HH:mm:ss.SSSXXX");

    /** Owner id. **/
    protected String ownerId;

    /** Recipient name. **/
    protected String recipientName;

    /** Recipient email. **/
    protected String recipientEmail;

    /** Weather Zipcode. **/
    protected String zipcode;

    /** Timezone. **/
    protected TimeZone timezone;

    /** Last-sent. **/
    protected Date nextSend;

    /** Key. **/
    protected long key;

    public WeatherEmailSchedule(String ownerId, String recipientName,
            String recipientEmail, String zipcode, TimeZone timezone,
            Date nextSend) {

        this.ownerId = ownerId;
        this.recipientName = recipientName;
        this.recipientEmail = recipientEmail;
        this.zipcode = zipcode;
        this.timezone = timezone != null ? (TimeZone) timezone.clone() : null;
        this.nextSend = nextSend != null ? (Date) nextSend.clone() : null;
    }

    public WeatherEmailSchedule(String ownerId, String recipientName,
            String recipientEmail, String zipcode, TimeZone timezone,
            Date nextSend, long key) {

        this(ownerId, recipientName, recipientEmail, zipcode, timezone,
                nextSend);
        this.key = key;
    }

    public String getOwnerId() {
        return this.ownerId;
    }

    public String getRecipientName() {
        return this.recipientName;
    }

    public String getRecipientEmail() {
        return this.recipientEmail;
    }

    public String getZipcode() {
        return this.zipcode;
    }

    public TimeZone getTimezone() {
        return this.timezone;
    }

    public Date getNextSend() {
        return this.nextSend != null ? (Date)this.nextSend.clone() : null;
    }

    public void setKey(long key) {
        this.key = key;
    }

    public long getKey() {
        return this.key;
    }

    public Date sendNow() {
        Calendar today = Calendar.getInstance(this.timezone);
        Calendar newLastSent = Calendar.getInstance(this.timezone);
        newLastSent.setTime(this.nextSend);

        newLastSent.set(today.get(Calendar.YEAR), today.get(Calendar.MONTH),
                today.get(Calendar.DAY_OF_MONTH));
        newLastSent.add(Calendar.DAY_OF_MONTH, 1);

        this.nextSend = newLastSent.getTime();

        return (Date)this.nextSend.clone();
    }

    /**
     * Converts the object in a Map of String:String which is useful for
     * formatting into JSON.
     * 
     * @return the object as a map of string-to-string.
     */
    public Map<String, String> toMap() {
        Map<String, String> map = new HashMap<String, String>();
        map.put("ownerId", getOwnerId());
        map.put("recipientName", getRecipientName());
        map.put("recipientEmail", getRecipientEmail());
        map.put("zipcode", getZipcode());
        map.put("timezone", timezone.getID());
        if (nextSend != null) {
            map.put("nextSend", String.valueOf(nextSend.getTime()));
            map.put("nextSendFormatted", sdf.format(nextSend.getTime()));
        } else {
            map.put("nextSend", "");
            map.put("nextSendFormatted", "");
        }
        map.put("key", String.valueOf(key));

        return map;
    }
}
